[package]
name = "NeoClef"
version = "0.1.0"
edition = "2024"

[dependencies]
midly = "0.5.3"
quick-xml = "0.39.0"
thiserror = "2.0.18"
log = "0.4.29"
env_logger = "0.11.8"

[dev-dependencies]
insta = "1.43.1"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
